# Generated by Django 3.1.3 on 2020-11-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_note_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='label',
            field=models.CharField(default='note', max_length=10),
            preserve_default=False,
        ),
    ]
