# Generated by Django 3.1.3 on 2020-11-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_note_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
