# Generated by Django 3.1.3 on 2020-12-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201129_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
