# Generated by Django 3.1.3 on 2020-12-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
