# Generated by Django 3.1.3 on 2020-12-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_notesofuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesofuser',
            name='note',
            field=models.CharField(max_length=200),
        ),
    ]
