# Generated by Django 3.1.3 on 2020-12-03 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201203_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesofuser',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.note'),
        ),
    ]
