# Generated by Django 3.1.3 on 2020-12-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201203_2003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModRequests',
        ),
    ]
