# Generated by Django 3.1.3 on 2020-12-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_modrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modrequests',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
