# Generated by Django 3.1.3 on 2021-01-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_announcements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcements',
        ),
    ]
